# Generated by Django 4.0.4 on 2022-05-24 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journal_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 9, 23, 20, 333354), null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 9, 23, 20, 333354), null=True),
        ),
    ]
