# Generated by Django 4.0.4 on 2022-05-24 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_created_at_alter_journal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 9, 24, 0, 949374, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 9, 24, 0, 949374, tzinfo=utc), null=True),
        ),
    ]
